# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\",\n\x0bHistoryList\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"Y\n\x0fQuestionRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\"\n\x07history\x18\x02 \x03(\x0b\x32\x11.chat.HistoryList\x12\x13\n\x0bisStreaming\x18\x03 \x01(\x08\" \n\x0e\x41nswerResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t2?\n\x04\x43hat\x12\x37\n\x06\x41nswer\x12\x15.chat.QuestionRequest\x1a\x14.chat.AnswerResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HISTORYLIST']._serialized_start=20
  _globals['_HISTORYLIST']._serialized_end=64
  _globals['_QUESTIONREQUEST']._serialized_start=66
  _globals['_QUESTIONREQUEST']._serialized_end=155
  _globals['_ANSWERRESPONSE']._serialized_start=157
  _globals['_ANSWERRESPONSE']._serialized_end=189
  _globals['_CHAT']._serialized_start=191
  _globals['_CHAT']._serialized_end=254
# @@protoc_insertion_point(module_scope)
