FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./src ./src
COPY .env.production .env.production

EXPOSE 8123
ENV ENV=production

CMD ["chainlit", "run", "src/app.py", "--host", "0.0.0.0", "--port", "8123"]