name: medical_chatbot
version: '3.5'

services:
  frontend:
    build: ./frontend
    env_file:
      - .env
    container_name: medical-chatbot-ui
    image: medical-chatbot-ui:latest
    environment:
      BACKEND_HOST: localhost
      BACKEND_PORT: 8001
      HTTP_TIMEOUT: 60      # Timeout for Chatbot to respond
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: CHAINLIT_DB
      POSTGRES_PASSWORD: CHAINLIT_DB
      POSTGRES_DB: MEDICAL_CHAT_HISTORY
    ports:
      - "8000:8000" # Chainlit UI
    depends_on:
      - db
  
  backend:
    build: ./backend
    env_file:
      - .env
    container_name: medical-backend
    image: medical-chatbot-backend:latest
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: CHAINLIT_DB
      POSTGRES_PASSWORD: CHAINLIT_DB
      POSTGRES_DB: MEDICAL_CHAT_HISTORY
    ports:
      - "8001:8001" # FastAPI backend=
    depends_on:
      - db
      - chatbot

  chatbot:
    build: ./chatbot
    env_file:
      - .env
    container_name: medical-chatbot
    image: medical-chatbot:latest
    environment:
      MILVUS_HOST: milvus-standalone
      MILVUS_PORT: 19530
      MILVUS_COLLECTION: medical_QA_embedding
      LANGFUSE_AVAILABLE: False # Do not used Langfuse
      # DEVICE: mps
      # PYTORCH_ENABLE_MPS_FALLBACK: 1 # Enable MPS fallback for PyTorch
    ports:
      - "50051:50051" # gRPC port           
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface # Cache for Hugging Face models
    depends_on:
      - standalone
      - minio
      - etcd

  db:
    image: postgres:latest
    container_name: medical-chatbot-ui-db
    environment:
      POSTGRES_USER: CHAINLIT_DB
      POSTGRES_PASSWORD: CHAINLIT_DB
      POSTGRES_DB: MEDICAL_CHAT_HISTORY
      PGUSER: CHAINLIT_DB
    ports:
      - "5432:5432"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/postgres:/var/lib/postgresql/data
      - ${DOCKER_VOLUME_DIRECTORY:-.}/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "CHAINLIT_DB", "-d", "MEDICAL_CHAT_HISTORY"]
      interval: 60s
      timeout: 10s
      retries: 3

  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.18
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.6.0-rc1
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      MQ_TYPE: woodpecker
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: medical-chatbot-network