apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: medical-chatbot-backend:latest
        ports:
        - containerPort: 8001
        env:
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: medical-chatbot-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: medical-secrets
              key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: medical-backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001