apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: milvus-s3-sa
      containers:
      - name: backend
        image: 376276261088.dkr.ecr.us-east-1.amazonaws.com/medical-chatbot/backend@sha256:b0e3d2ee59c26f90aa20f7a59389bc3b6f3499a0c26efac6e95ce1782ce6c59c
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: medical-chatbot-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: medical-chatbot-config
              key: POSTGRES_PORT
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: medical-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: medical-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: medical-chatbot-config
              key: POSTGRES_DB
        - name: GRPC_HOST
          valueFrom:
            configMapKeyRef:
              name: medical-chatbot-config
              key: GRPC_HOST
        - name: GRPC_PORT
          valueFrom:
            configMapKeyRef:
              name: medical-chatbot-config
              key: GRPC_PORT
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "medical-secrets-provider"
---
apiVersion: v1
kind: Service
metadata:
  name: medical-backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001