apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      serviceAccountName: milvus-s3-sa
      containers:
      - name: chatbot
        image: 376276261088.dkr.ecr.us-east-1.amazonaws.com/medical-chatbot/inference:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: medical-secrets
              key: OPENAI_API_KEY
        - name: MILVUS_HOST
          valueFrom:
            configMapKeyRef:
              name: medical-chatbot-config
              key: MILVUS_HOST
        - name: MILVUS_PORT
          valueFrom:
            configMapKeyRef:
              name: medical-chatbot-config
              key: MILVUS_PORT
        - name: MILVUS_COLLECTION
          valueFrom:
            configMapKeyRef:
              name: medical-chatbot-config
              key: MILVUS_COLLECTION
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "medical-secrets-provider"
              
---
apiVersion: v1
kind: Service
metadata:
  name: medical-chatbot-service
spec:
  selector:
    app: chatbot
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051