apiVersion: v1
kind: ConfigMap
metadata:
  name: medical-chatbot-config
data:
  # ========== FRONTEND SERVICE ==========
  BACKEND_HOST: "medical-backend-service"            # FastAPI backend service DNS
  BACKEND_PORT: "8001"
  HTTP_TIMEOUT: "600"                         # Timeout for Chatbot to respond
  POSTGRES_HOST: "medical-chatbot-db.cidauo64mf0l.us-east-1.rds.amazonaws.com"          # PostgreSQL service DNS
  POSTGRES_PORT: "5432"
  # POSTGRES_USER: "CHAINLIT_DB"                       # Moved to Secret for better security
  POSTGRES_DB: "MEDICAL_CHAT_HISTORY"

  # ========== BACKEND SERVICE ==========
  # Uses POSTGRES_* from above for database connection

  # ========== CHATBOT SERVICE ==========
  MILVUS_HOST: "milvus-standalone"           # Milvus service DNS
  MILVUS_PORT: "19530"
  MILVUS_COLLECTION: "medical_QA_embedding"
  # DEVICE: "cpu"                              # cpu | mps | cuda (based on infrastructure)

  # ========== ETCD SERVICE ==========
  ETCD_AUTO_COMPACTION_MODE: "revision"
  ETCD_AUTO_COMPACTION_RETENTION: "1000"
  ETCD_QUOTA_BACKEND_BYTES: "4294967296"
  ETCD_SNAPSHOT_COUNT: "50000"
  ETCD_ENDPOINTS: "etcd:2379"                # For Milvus to connect to etcd

  # ========== S3/MINIO SERVICE ==========
  MINIO_ADDRESS: "s3.us-east-1.amazonaws.com"                # For Milvus to connect to MinIO
  MINIO_PORT: "443"
  MINIO_USE_SSL: "true"
  MINIO_BUCKET_NAME: "medical-chatbot-data-bucket-376276261088-us-east-1-an"
  # ========== MILVUS (STANDALONE) SERVICE ==========
  MQ_TYPE: "woodpecker"

  #========== GRPC SERVICE ==========
  GRPC_HOST: "medical-chatbot-service"       # For Backend to connect to Chat
  GRPC_PORT: "50051"
  # ========== GLOBAL/SHARED CONFIG ==========
  ENV: "production"                          # development | staging | production


  # ========== MILVUS OVERRIDE CONFIG ==========
  user.yaml: |
    minio:
      address: s3.us-east-1.amazonaws.com
      port: 443
      useSSL: true
      bucketName: medical-chatbot-data-bucket-376276261088-us-east-1-an
      useIAM: true
      cloudProvider: aws
      iamEndpoint: ""
      region: us-east-1