apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: milvus-s3-sa
      containers:
      - name: frontend
        image: 376276261088.dkr.ecr.us-east-1.amazonaws.com/medical-chatbot/frontend@sha256:88219d1e84f28660a4801a1dfed53e7128e932992587c78f426bd834470da717
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: BACKEND_HOST
          valueFrom:
            configMapKeyRef:
              name: medical-chatbot-config
              key: BACKEND_HOST
        - name: BACKEND_PORT
          valueFrom:
            configMapKeyRef:
              name: medical-chatbot-config
              key: BACKEND_PORT
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: medical-chatbot-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: medical-chatbot-config
              key: POSTGRES_PORT
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: medical-secrets
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: medical-chatbot-config
              key: POSTGRES_DB
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: medical-secrets
              key: POSTGRES_PASSWORD
        - name: CHAINLIT_AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: medical-secrets
              key: CHAINLIT_AUTH_SECRET
        - name: HTTP_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: medical-chatbot-config
              key: HTTP_TIMEOUT
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "medical-secrets-provider"
---
apiVersion: v1
kind: Service
metadata:
  name: medical-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000