apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: medical-chatbot-ui:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: BACKEND_HOST
          valueFrom:
            configMapKeyRef:
              name: medical-chatbot-config
              key: BACKEND_HOST
        - name: BACKEND_PORT
          valueFrom:
            configMapKeyRef:
              name: medical-chatbot-config
              key: BACKEND_PORT
        - name: CHAINLIT_AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: medical-secrets
              key: CHAINLIT_AUTH_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: medical-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000