apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: medical-chatbot

resources:
  - configmap.yaml
  - postgres-storage.yaml
  - frontend-deployment.yaml
  - backend-deployment.yaml
  - chatbot-deployment.yaml
