apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: medical-chatbot

resources:
  - configmap.yaml
  - secret-provider.yaml
  # - postgres-storage.yaml # Switched to AWS RDS, so PostgreSQL storage is no longer needed
  # - postgres-deployment.yaml # Switched to AWS RDS, so PostgreSQL deployment is no longer needed
  - gp3-storage-class.yaml
  - milvus-storage.yaml
  - milvus-etcd-deployment.yaml
  # - milvus-minio-deployment.yaml    # Switched to AWS S3, so MinIO deployment is no longer needed
  - milvus-standalone-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - chatbot-deployment.yaml

