apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus-standalone
  namespace: medical-chatbot
spec:
  selector:
    matchLabels:
      app: milvus
  template:
    metadata:
      labels:
        app: milvus
    spec:
      containers:
      - name: milvus
        image: milvusdb/milvus:v2.6.0-rc1
        command: ["milvus", "run", "standalone"]
        env:
        - name: ETCD_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              name: medical-chatbot-config
              key: ETCD_ENDPOINTS
        - name: MINIO_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: medical-chatbot-config
              key: MINIO_ADDRESS
        ports:
        - containerPort: 19530
---
apiVersion: v1
kind: Service
metadata:
  name: milvus-standalone
  namespace: medical-chatbot
spec:
  selector:
    app: milvus
  ports:
    - port: 19530
      targetPort: 19530