apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-pvc
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: gp3
  resources:
    requests:
      storage: 1Gi
      # On EKS,  ensure this PVC is backed by an AWS storage class (like gp3)