apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus-standalone
  namespace: medical-chatbot
spec:
  selector:
    matchLabels:
      app: milvus
  template:
    metadata:
      labels:
        app: milvus
    spec:
      serviceAccountName: milvus-s3-sa
      containers:
      - name: milvus
        image: 376276261088.dkr.ecr.us-east-1.amazonaws.com/medical-chatbot/milvus:v2.6.0-rc1
        command: ["milvus", "run", "standalone"]
        env:
        - name: ETCD_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              name: medical-chatbot-config
              key: ETCD_ENDPOINTS
        - name: MINIO_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: medical-chatbot-config
              key: MINIO_ADDRESS
        - name: MINIO_PORT
          valueFrom:
            configMapKeyRef:
              name: medical-chatbot-config
              key: MINIO_PORT
        - name: MINIO_USE_SSL
          valueFrom:
            configMapKeyRef:
              name: medical-chatbot-config
              key: MINIO_USE_SSL
        - name: MINIO_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: medical-chatbot-config
              key: MINIO_BUCKET_NAME
        volumeMounts:
        - name: milvus-config
          mountPath: /milvus/configs/user.yaml
          subPath: user.yaml
        ports:
        - containerPort: 19530
      volumes:
      - name: milvus-config
        configMap:
          name: medical-chatbot-config
---
apiVersion: v1
kind: Service
metadata:
  name: milvus-standalone
  namespace: medical-chatbot
spec:
  selector:
    app: milvus
  ports:
    - port: 19530
      targetPort: 19530