apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  namespace: medical-chatbot
spec:
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: 376276261088.dkr.ecr.us-east-1.amazonaws.com/medical-chatbot/etcd:v3.5.18
        env:
        - name: ETCD_AUTO_COMPACTION_MODE
          valueFrom:
            configMapKeyRef:
              name: medical-chatbot-config
              key: ETCD_AUTO_COMPACTION_MODE  
        - name: ETCD_AUTO_COMPACTION_RETENTION
          valueFrom:
            configMapKeyRef:
              name: medical-chatbot-config
              key: ETCD_AUTO_COMPACTION_RETENTION
        command: ["etcd", "-advertise-client-urls=http://etcd:2379", "-listen-client-urls=http://0.0.0.0:2379", "--data-dir=/etcd"]
        volumeMounts:
        - name: etcd-data
          mountPath: /etcd
      volumes:
      - name: etcd-data
        persistentVolumeClaim:
          claimName: etcd-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: medical-chatbot
spec:
  selector:
    app: etcd
  ports:
    - port: 2379
      targetPort: 2379