apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: medical-secrets-provider
  namespace: medical-chatbot
spec:
  provider: aws
  secretObjects:
  - secretName: medical-secrets
    type: Opaque
    data:
    - objectName: "OPENAI_API_KEY"
      key: OPENAI_API_KEY
    - objectName: "POSTGRES_PASSWORD"
      key: POSTGRES_PASSWORD
  parameters:
    objects: |
      - objectName: "medical-chatbot/app-credentials"
        jmesPath:
          - path: "OPENAI_API_KEY"
            objectAlias: "OPENAI_API_KEY"
      - objectName: "rds!db-424649ea-d988-48f3-8364-8fdda0577608-jR5Rrb"
        jmesPath:
          - path: "password"
            objectAlias: "POSTGRES_PASSWORD"